@startuml organization
skinparam dpi 300

() RecordingLib
() SoundLibrary
() FastWaveletTransform
() SQLiteLib

package VoiceAppGUI {
    class VocalStats {}

    class VoiceAnalyzer {
        + VoiceAnalyzer()
        + VocalStats getSnapshot()
        + void beginPlayStreamWithDelay(double s)
        + void endPlayStreamWithDelay()
    }

    package HomePage {
        () "navigation" as nav1
    }

    package AnalysisPage {
        class DisplayWidget {}
    }

    package PassthroughPage {
        class PassThroughInterface {}
    }

    package GamificationPage {
        class StateManager {}
    }

    package InfoPage {}

    nav1 --> AnalysisPage
    nav1 --> PassthroughPage
    nav1 --> GamificationPage
    nav1 --> InfoPage

    DisplayWidget -- VocalStats : Gets snapshots >
    VocalStats -- VoiceAnalyzer : Loads frequency information >
    PassThroughInterface -- VoiceAnalyzer : Gets passthrough with arbitrary delay >
}

VoiceAnalyzer -- RecordingLib : Gets microphone input from >
VoiceAnalyzer -- SoundLibrary : Plays sound via >
VoiceAnalyzer -- FastWaveletTransform : Analyzes input via >
StateManager -- SQLiteLib : Stores data via >

() main
main --> HomePage : Default

@enduml
