@startuml organization
skinparam dpi 300

() RecordingLib
() SoundLibrary
() PitchDetector

package VoiceAppGUI {
    class VocalStats {}

    class VoiceAnalyzer {
        + VoiceAnalyzer()
        + void dispose()
        + VocalStats getSnapshot()
        + void beginSnapshots(callback)
        + void endSnapshots()
        + void beginPlayStreamWithDelay(double s)
        + void endPlayStreamWithDelay()
    }

    package HomePage {
        () "navigation" as nav1
    }

    package AnalysisPage {
        class DisplayWidget {}
    }

    package PassthroughPage {
        class PassThroughInterface {}
    }

    package InfoPage {}

    nav1 -> AnalysisPage
    nav1 -> PassthroughPage
    nav1 -> InfoPage

    DisplayWidget -- VocalStats : Gets snapshots >
    VocalStats -- VoiceAnalyzer : Loads frequency information >
    PassThroughInterface -- VoiceAnalyzer : Gets passthrough with arbitrary delay >
}

VoiceAnalyzer -- RecordingLib : Gets microphone input from >
VoiceAnalyzer -- SoundLibrary : Plays sound via >
VoiceAnalyzer -- Formants : Uses to get F1 >
VoiceAnalyzer -- PitchDetector : Uses to get F0 >

() main
main --> HomePage : Default

class Formants {
    + Future<double> getF1(signal, double f0, double sampleRate)
}

@enduml
