.PHONY:	all
all:
	python3 ../formant_generator.py 150 600 1500 lowlow.wav
	python3 ../formant_generator.py 150 2000 1500 lowhi.wav
	python3 ../formant_generator.py 500 600 1500 hilow.wav
	python3 ../formant_generator.py 500 2000 1500 hihi.wav
